apiVersion: v1
kind: Service
metadata:
  name: certbot
  labels:
    name: certbot
    tier: addon
spec:
  selector:
    name: certbot
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: certbot
spec:
  replicas: 1
  template:
    metadata:
      name: certbot
      labels:
        app: certbot
    spec:
      containers:
      # - name: nginx
      #   image: nginx:alpine
      - name: certbot
        image: certbot
        # command: ["certbot", "certonly", "--email", "engineering@orbweb.com", "--agree-tos", "-standalone", "--manual-public-ip-logging-ok"]
        ports:
        - name: http
          containerPort: 80
        # env:
        #   - name: TLS_SECRET_NAME
        #     value: ssl-example-com
      - name: k8s-certbot
        image: k8s-certbot
        # /etc/letsencrypt/live/iii.gotomythings.com/fullchain.pem
